### ISSUE TITLE
no function named "assert-ture"

### ISSUE THREAD

**Issue by hisoka176** [google/lisp-koans#75]
above

**Comment by rowanthorpe** [comment]
Grepping the repository, I didn't find any occurrence of `assert-ture` anywhere, so I grepped through the content of `git log -p` right back to the initial commit and couldn't find any historical occurrence of it either. I suspect you will need to give more detail of what this problem is for you - and where - for someone to be able to help.

**Comment by Slids** [comment]
I'm finding no instance of this, and no response to @rowanthorpe  in 3 years so closing.
